# Generated by Django 4.1.3 on 2022-11-30 10:44

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street and number of a building.",
                        max_length=100,
                        verbose_name="Street",
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        help_text="Postal code.",
                        max_length=10,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City", max_length=100, verbose_name="City"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Address longitude.",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Address latitude.",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of a child.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of a child.",
                        max_length=254,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Child's letter to Santa.",
                        verbose_name="Letter to Santa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("READY_FOR_SHIPPING", "Ready for shipping"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="NEW",
                        help_text="Status of a wish list.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="An automatically generated slug (can be used to construct URLs).",
                        populate_from="name",
                        verbose_name="Slug",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        help_text="An address where the presents will be delivered.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wish_lists",
                        related_query_name="wish_list",
                        to="wishes.address",
                        verbose_name="A child's address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of a present.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Approved by Santa.",
                        verbose_name="Approved",
                    ),
                ),
                (
                    "wish_list",
                    models.ForeignKey(
                        help_text="A relevant wish list the present belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        related_query_name="item",
                        to="wishes.wishlist",
                        verbose_name="A wish list",
                    ),
                ),
            ],
        ),
    ]
