# Generated by Django 4.1.3 on 2022-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishes", "0002_wishlistaccepted_wishlistdelivered_wishlistnew_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="wishlistaccepted",
            options={
                "verbose_name": "accepted wish list",
                "verbose_name_plural": "2. Accepted wish lists",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlistdelivered",
            options={
                "verbose_name": "delivered wish list",
                "verbose_name_plural": "5. Delivered wish lists",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlistnew",
            options={
                "verbose_name": "new wish list",
                "verbose_name_plural": "1. New wish lists",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlistreadyforshipping",
            options={
                "verbose_name": "wish list ready for shipping",
                "verbose_name_plural": "4. Wish lists ready for shipping",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlistrejected",
            options={
                "verbose_name": "rejected wish list",
                "verbose_name_plural": "3. Rejected wish lists",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="lat",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Address latitude.",
                max_digits=9,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="lng",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Address longitude.",
                max_digits=9,
                verbose_name="Longitude",
            ),
        ),
    ]
